dist: xenial

install:
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"
  - sudo apt-get update -q
  - sudo apt-get install linux-headers-generic linux-headers-$(uname -r) virtualbox-5.1
  - sudo apt-get install vagrant
  - curl -O https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
  - sudo dpkg -i vagrant_2.2.4_x86_64.deb

script:
  - vagrant up --provider=virtualbox
  - test $(curl --write-out "%{http_code}\n" --silent --output /dev/null "http://localhost:8081") -eq 200
  - test $(curl --write-out "%{http_code}\n" --silent --output /dev/null -u prometheus:prometheus "http://localhost:8081/prometheus/graph") -eq 200

after_script:
  - vagrant destroy -f