dist: xenial

install:
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"
  - sudo apt-get update -q
  - sudo apt-get install linux-headers-generic virtualbox-6.0
  - sudo apt-get install vagrant

script:
  - vagrant up

after_script:
  - vagrant destroy -f