- name: cloudalchemy.prometheus
  version: 2.11.0
- name: nginxinc.nginx
  version: 0.12.0
- name: cloudalchemy.grafana
  version: 0.16.2
- name: cloudalchemy.node-exporter
  version: 0.16.0
- name: cloudalchemy.blackbox-exporter
  version: 0.8.0
